-- SQL
SELECT * FROM AUTORES;
SELECT * FROM CATEGORIAS;
SELECT * FROM LIVROS;

-- SELECIONE O AUTOR BUSCANDO UM NOME ESPECIFICO
SELECT
	*
	FROM AUTORES WHERE AUTOR = "Robert Downey Jr";
    
-- SELECIONE O NOME DOS AUTORES COM SEUS RESPECTIVOS LIVROS
SELECT
AUTOR AS "NOME DO AUTOR",
TITULO AS "TITULO DO LIVRO"
FROM AUTORES
INNER JOIN LIVROS
ON AUTORES.ID = LIVROS.AUTOR_ID;
 
-- SELECIONAR OS LIVROS MAIS RECENTE
SELECT
	*
    FROM LIVROS
    ORDER BY DATA_LANCAMENTO DESC;
    
-- SELECIONAR DADOS DOS LIVROS POR COMPLETO
SELECT 
AUTOR AS "AUTOR",
TITULO AS "TITULO",
CATEGORIA AS "CATEGORIA",
DATA_LANCAMENTO AS "DATA DE LANÇAMENTO DO LIVRO",
DESCRICAO AS "DESCRICAO"
FROM LIVROS
INNER JOIN AUTORES ON LIVROS.AUTOR_ID = AUTORES.ID
INNER JOIN CATEGORIAS ON LIVROS.CATEGORIA_ID = CATEGORIAS.ID;

-- USANDO LEFT/RIGHT
SELECT
AUTOR AS "AUTOR",
TITULO AS "TITULO"
FROM LIVROS
LEFT JOIN AUTORES ON LIVROS.AUTOR_ID = AUTORES.ID;

SELECT
AUTOR AS "AUTOR",
TITULO AS "TITULO"
FROM LIVROS
RIGHT JOIN AUTORES ON LIVROS.AUTOR_ID = AUTORES.ID;

-- BUSCANDO DADOS COM DUPLICIDADE
SELECT 
ID AS "ID",
TITULO AS "TITULOS REPETIDOS",
COUNT(*)
FROM LIVROS
GROUP BY TITULO
HAVING COUNT(*) > 1;

-- -----------
SELECT
	*
    FROM LIVROS
    WHERE TITULO = "Thor O Deus do Trovão";
