-- SQL
SELECT * FROM AUTORES;
SELECT * FROM CATEGORIAS;
SELECT * FROM LIVROS;

-- SELECIONE O AUTOR BUSCANDO UM NOME ESPECIFICO
SELECT
	*
	FROM AUTORES WHERE AUTOR = "Robert Downey Jr";
    
-- SELECIONE O NOME DOS AUTORES COM SEUS RESPECTIVOS LIVROS
SELECT
AUTOR AS "NOME DO AUTOR",
TITULO AS "TITULO DO LIVRO"
FROM AUTORES
INNER JOIN LIVROS
ON AUTORES.ID = LIVROS.AUTOR_ID;
 
