-- SQL
SELECT * FROM USUARIOS;
SELECT * FROM ALUNOS;
SELECT * FROM DISCIPLINAS;
SELECT * FROM ESCOLAS;

-- SELECIONAR NOME DO ADMINISTRADOR REGISTRADO
SELECT
USUARIO_NOME AS "NOME DO ADMINISTRADOR"
FROM USUARIOS
WHERE IS_ADMIN = TRUE;

-- SELECIONAR EM QUAL ESCOLA OS ALUNOS ESTAO RELACIONADOS
SELECT
ALUNO_NOME AS "ALUNO",
INSTITUICAO AS "ESCOLA"
FROM ESCOLAS
INNER JOIN ALUNOS
ON ESCOLAS.ALUNO_ID = ALUNOS.ID;


SELECT
USUARIO_NOME AS "PROFESSOR",
ALUNO_NOME AS "ALUNO",
DISCIPLINA_NOME AS "DISCIPLINAS",
INSTITUICAO AS "ESCOLA"
FROM ALUNOS
INNER JOIN DISCIPLINAS
ON ALUNOS.ID = DISCIPLINAS.ALUNO_ID
INNER JOIN USUARIOS
ON USUARIOS.ID = DISCIPLINAS.USUARIO_ID
INNER JOIN ESCOLAS
ON ESCOLAS.ALUNO_ID = ALUNOS.ID;

