-- CRIAR BANCO DE DADOS "CONTROL"
CREATE DATABASE CONTROL;

-- USAR BANCO DE DADOS "CONTROL"
USE CONTROL;

-- CRIANDO TABELAS
CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
    USUARIO_NOME VARCHAR(50) NOT NULL,
    USUARIO_EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    IS_ADMIN BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE ALUNOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ALUNO_NOME VARCHAR(50) NOT NULL,
    ALUNO_RA INT NOT NULL
);

CREATE TABLE DISCIPLINAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DISCIPLINA_NOME VARCHAR(50) NOT NULL,
    USUARIO_ID INT NOT NULL,
    ALUNO_ID INT NOT NULL,
    
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID)
);

CREATE TABLE ESCOLAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    INSTITUICAO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    USUARIO_ID INT NOT NULL,
    ALUNO_ID INT NOT NULL,
    DISCIPLINA_ID INT NOT NULL,
    
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID),
    FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINAS(ID)
);