-- CRIAR BANCO DE DADOS "CONTROLBOOK"
CREATE DATABASE CONTROLBOOK;

-- USAR BANCO DE DADOS "CONTROLBOOK"
USE CONTROLBOOK;

-- CRIANDO TABELAS
CREATE TABLE AUTORES(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
    AUTOR VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL
);

CREATE TABLE CATEGORIAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE LIVROS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    AUTOR_ID INT NOT NULL,
    CATEGORIA_ID INT NOT NULL,
    
    FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES(ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
);
